#!/usr/bin/env python3
"""
Jarvis Setup Wizard
Interactive CLI to configure Jarvis for the first time.
"""

import os
import sys
import shutil
from pathlib import Path

# ANSI colors
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header():
    print(f"\n{Colors.HEADER}{Colors.BOLD}🤖 Jarvis AI Assistant - Setup Wizard{Colors.END}")
    print(f"{Colors.BLUE}======================================={Colors.END}\n")

def input_clean(prompt, default=None):
    if default:
        user_input = input(f"{Colors.CYAN}{prompt} [{default}]: {Colors.END}").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{Colors.CYAN}{prompt}: {Colors.END}").strip()
            if user_input:
                return user_input
            print(f"{Colors.WARNING}This field is required.{Colors.END}")

def main():
    print_header()
    
    # 1. Project Paths
    current_dir = Path(__file__).parent.resolve()
    project_root = current_dir.parent.resolve() # jarvis root (where package.json and python/ dir are)
    py_dir = current_dir

    print(f"📂 Setting up Jarvis in: {project_root}")
    
    # 2. Check for .env
    env_path = py_dir / ".env"
    existing_env = {}
    
    if env_path.exists():
        print(f"{Colors.GREEN}✅ Found existing .env file.{Colors.END}")
        try:
            with open(env_path, 'r') as f:
                for line in f:
                    if '=' in line and not line.startswith('#'):
                        k, v = line.strip().split('=', 1)
                        existing_env[k] = v
        except Exception:
            pass
    else:
        print(f"{Colors.WARNING}⚠️ No .env file found. Let's create one.{Colors.END}")

    # 3. Ask for API Keys
    print(f"\n{Colors.BOLD}🔑 API Configuration{Colors.END}")
    print("You need a Google Gemini API Key. Get one at: https://aistudio.google.com/app/apikey")
    
    gemini_key = input_clean("Gemini API Key", existing_env.get("GEMINI_API_KEY"))
    
    print("\n(Optional) Groq API Key for fast inference (Llama 3)")
    groq_key = input_clean("Groq API Key (press Enter to skip)", existing_env.get("GROQ_API_KEY") or "")
    
    print("\n(Optional) Picovoice Access Key for Wake Word ('Hey Jarvis')")
    picovoice_key = input_clean("Picovoice Key (press Enter to skip)", existing_env.get("PICOVOICE_ACCESS_KEY") or "")
    
    # 4. User Profile
    print(f"\n{Colors.BOLD}👤 User Profile{Colors.END}")
    user_name = input_clean("Your Name", "User")
    
    # 5. Create/Update .env
    env_content = f"""# Jarvis Configuration
# Generated by Setup Wizard

# --- API Keys ---
GEMINI_API_KEY={gemini_key}
GROQ_API_KEY={groq_key}
PICOVOICE_ACCESS_KEY={picovoice_key}

# --- Optional Keys ---
# TAVILY_API_KEY=
# OPENROUTER_API_KEY=
# CEREBRAS_API_KEY=

# --- Feature Flags ---
JARVIS_DEBUG=false
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n{Colors.GREEN}✅ .env file created!{Colors.END}")

    # 6. Create User Directories
    user_jarvis_dir = Path.home() / ".jarvis"
    skills_dir = user_jarvis_dir / "skills"
    backups_dir = user_jarvis_dir / "backups"
    
    for d in [user_jarvis_dir, skills_dir, backups_dir]:
        d.mkdir(parents=True, exist_ok=True)
        print(f"📂 Verified directory: {d}")

    # 7. Add Fact about Name
    # This is a bit tricky since we need the DB initialized.
    # We'll just append it to a temporary facts file or rely on first run.
    # Actually, let's try to initialize the DB and add it directly.
    print(f"\n{Colors.BOLD}💾 Initializing Database...{Colors.END}")
    try:
        sys.path.insert(0, str(py_dir))
        from core.memory import init_database, add_fact
        init_database()
        add_fact(f"The user's name is {user_name}.")
        print(f"{Colors.GREEN}✅ Saved your name to memory.{Colors.END}")
    except Exception as e:
        print(f"{Colors.WARNING}⚠️ Could not access database: {e}{Colors.END}")

    # 8. Setup SOUL.md
    print(f"\n{Colors.BOLD}👻 Setting up AI Personality (SOUL)...{Colors.END}")
    soul_src = py_dir / "data" / "SOUL.md"
    
    # If it doesn't exist in source check if we can create default
    if not soul_src.exists():
         # It should have been created by previous steps, but just in case
         pass

    # We use the one in repo as the source of truth for now.
    # Ideally we Copy it to ~/.jarvis/SOUL.md so user can edit it without git dirtying?
    # For now, let's keep it in the repo as per our plan.
    if soul_src.exists():
         print(f"{Colors.GREEN}✅ SOUL.md found in data directory.{Colors.END}")
         print(f"   You can edit this file to change Jarvis's personality: {soul_src}")
    
    # 9. Install Launch Agent?
    print(f"\n{Colors.BOLD}🚀 Auto-Start Configuration{Colors.END}")
    install_agent = input_clean("Do you want Jarvis to start automatically on login? (y/n)", "y").lower() == 'y'
    
    if install_agent:
        plist_src = py_dir / "com.jarvis.menu.plist"
        plist_dest = Path.home() / "Library/LaunchAgents/com.jarvis.menu.plist"
        
        # We need to update the paths in the plist to match the current location
        if plist_src.exists():
            with open(plist_src, 'r') as f:
                content = f.read()
            
            # Simple replace of the known paths
            # CAUTION: The plist has hardcoded paths from my dev machine.
            # We must replace them with current valid paths.
            
            python_executable = sys.executable
            script_path = str(py_dir / "jarvis_menu.py")
            
            # Use regex or simple replace if we know what to look for?
            # Better to just regenerate the plist content from scratch or template.
            
            # Let's generate a fresh plist content
            plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.jarvis.menu</string>

    <key>ProgramArguments</key>
    <array>
      <string>{python_executable}</string>
      <string>{script_path}</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <false/>

    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>

    <key>StandardOutPath</key>
    <string>/tmp/jarvis_menu.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/jarvis_menu.err.log</string>
  </dict>
</plist>
"""
            with open(plist_dest, 'w') as f:
                f.write(plist_content)
                
            print(f"{Colors.GREEN}✅ Launch Agent installed to {plist_dest}{Colors.END}")
            
            # Load it
            try:
                os.system(f"launchctl unload {plist_dest} 2>/dev/null")
                os.system(f"launchctl load {plist_dest}")
                print(f"{Colors.GREEN}✅ Jarvis scheduled to start!{Colors.END}")
            except Exception as e:
                print(f"{Colors.WARNING}⚠️ Could not load launch agent: {e}{Colors.END}")
        else:
             print(f"{Colors.FAIL}❌ Could not find source plist template.{Colors.END}")

    print(f"\n{Colors.HEADER}✨ Setup Complete! ✨{Colors.END}")
    print("To start Jarvis manually, run:")
    print(f"  {sys.executable} {py_dir}/jarvis_menu.py")
    print("\nEnjoy your AI companion!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
